set rtp+=~/.vim/bundle/vundle.vim
call vundle#begin()
Plugin 'gmarik/vundle.vim'
Plugin 'sirver/ultisnips'
Plugin 'raimondi/delimitMate'
Plugin 'mhinz/vim-signify'
Plugin 'bling/vim-airline'
Plugin 'tpope/vim-fugitive'
Plugin 'ludovicchabant/vim-lawrencium'
Plugin 'editorconfig/editorconfig-vim'
Plugin 'vim-scripts/preservenoeol'
Plugin 'scrooloose/syntastic'
Plugin 'jelera/vim-javascript-syntax'
Plugin 'toyamarinyon/vim-swift'
Plugin 'chriskempson/base16-vim'
call vundle#end()
